### ISSUE TITLE
Error module install with CLI

### ISSUE THREAD

**Issue by Yourdigitalheart** [sethbrasile/ghost-cloudinary-store#21]
Hello I got this error some idea?
`NAME: IncorrectUsageError
CODE: MODULE_NOT_FOUND
MESSAGE: We detected a misuse. Please read the stack trace.

level:critical

We cannot find your adapter in: /var/www/ghost/content/adapters/storage/ or: /var/www/ghost/versions/1.9.0/core/server/adapters/storage/
IncorrectUsageError: We detected a misuse. Please read the stack trace.
    at new IncorrectUsageError (/var/www/ghost/versions/1.9.0/node_modules/ghost-ignition/lib/errors/index.js:79:23)
    at Object.getStorage (/var/www/ghost/versions/1.9.0/core/server/adapters/storage/index.js:62:19)
    at setupBlogApp (/var/www/ghost/versions/1.9.0/core/server/blog/app.js:64:66)
    at setupParentApp (/var/www/ghost/versions/1.9.0/core/server/app.js:54:36)
    at /var/www/ghost/versions/1.9.0/core/server/index.js:70:37
    at tryCatcher (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Error: Cannot find module '/var/www/ghost/versions/1.9.0/core/server/adapters/storage/ghost-cloudinary-store'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.getStorage (/var/www/ghost/versions/1.9.0/core/server/adapters/storage/index.js:59:42)
    at setupBlogApp (/var/www/ghost/versions/1.9.0/core/server/blog/app.js:64:66)
    at setupParentApp (/var/www/ghost/versions/1.9.0/core/server/app.js:54:36)
    at /var/www/ghost/versions/1.9.0/core/server/index.js:70:37
    at tryCatcher (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:17:14)`

**Comment by Yourdigitalheart** [comment]
I fix my config.json
but I got 


ERROR [2017-09-28 15:45:35] "POST /ghost/api/v0.1/uploads/" 500 49ms

NAME: InternalServerError
MESSAGE: Cannot read property 'image' of undefined

level:normal

InternalServerError: Cannot read property 'image' of undefined
    at new GhostError (/var/www/ghost/versions/1.9.0/core/server/errors.js:9:26)
    at prepareError (/var/www/ghost/versions/1.9.0/core/server/middleware/error-handler.js:40:19)
    at Layer.handle_error (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:315:13)
    at /var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:275:10)
    at /var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/index.js:260:14)
    at next (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/route.js:127:14)
    at onAPIError (/var/www/ghost/versions/1.9.0/core/server/api/index.js:286:13)
    at tryCatcher (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

TypeError: Cannot read property 'image' of undefined
    at CloudinaryAdapter.save (/var/www/ghost/content/adapters/storage/cloudinary-store/index.js:27:60)
    at /var/www/ghost/versions/1.9.0/core/server/api/upload.js:24:22
    at tryCatcher (/var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/util.js:16:23)
    at /var/www/ghost/versions/1.9.0/node_modules/bluebird/js/release/method.js:15:34
    at apiHandler (/var/www/ghost/versions/1.9.0/core/server/api/index.js:264:16)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/route.js:137:13)
    at uploadValidation (/var/www/ghost/versions/1.9.0/core/server/middleware/validation/upload.js:28:9)
    at Layer.handle [as handle_request] (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/ghost/versions/1.9.0/node_modules/express/lib/router/route.js:137:13)
    at Immediate.<anonymous> (/var/www/ghost/versions/1.9.0/node_modules/multer/lib/make-middleware.js:53:37)
    at runCallback (timers.js:676:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by mmornati** [comment]
I think it can be the same problem than the one described into the [Issue 22](https://github.com/sethbrasile/ghost-cloudinary-store/issues/22).
Just try to check the configuration you have in your ghost for the cloudinary store:
```
"storage": {
    "active": "cloudinary-store",
    "cloudinary-store": {
      "configuration": {
        "image": {
          "quality": "auto:good",
          "secure": "true"
        },
        "file": {
          "use_filename": "true",
          "unique_filename": "false",
          "phash": "true",
          "overwrite": "false",
          "invalidate": "true"
        }
      }
    }
  },
```
